/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Intel_MediaSdk_FBOtoMediaSdk */

#ifndef _Included_Intel_MediaSdk_FBOtoMediaSdk
#define _Included_Intel_MediaSdk_FBOtoMediaSdk
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Intel_MediaSdk_FBOtoMediaSdk
 * Method:    FBOInit
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_Intel_MediaSdk_FBOtoMediaSdk_FBOInit
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Intel_MediaSdk_FBOtoMediaSdk
 * Method:    MsdkInit
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_Intel_MediaSdk_FBOtoMediaSdk_MsdkInit
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Intel_MediaSdk_FBOtoMediaSdk
 * Method:    FBOsetup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Intel_MediaSdk_FBOtoMediaSdk_FBOsetup
  (JNIEnv *, jobject);

/*
 * Class:     Intel_MediaSdk_FBOtoMediaSdk
 * Method:    cleanUp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Intel_MediaSdk_FBOtoMediaSdk_cleanUp
  (JNIEnv *, jobject);

/*
 * Class:     Intel_MediaSdk_FBOtoMediaSdk
 * Method:    processFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Intel_MediaSdk_FBOtoMediaSdk_processFrame
  (JNIEnv *, jobject);

/*
 * Class:     Intel_MediaSdk_FBOtoMediaSdk
 * Method:    hw_swSwap
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Intel_MediaSdk_FBOtoMediaSdk_hw_1swSwap
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
